graphhopper:
  datareader.file: /data/nanjing.osm.pbf
  graph.location: /data/graph-cache

  profiles:
    - name: foot
      custom_model_files: [foot.json]
  profiles_ch:
    - profile: foot
  profiles_lm: []

  graph.encoded_values: foot_access, foot_priority, foot_average_speed, foot_road_access, hike_rating, mtb_rating, country, road_class
  prepare.min_network_size: 50
  prepare.subnetworks.threads: 1
  graph.dataaccess.default_type: MMAP
  routing.timeout_ms: 30000
  routing.max_visited_nodes: 1000000

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
      max_request_header_size: 50k
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0
  request_log:
    appenders: []

logging:
  level: INFO
  appenders:
    - type: console
      time_zone: Asia/Shanghai
